# Generated by Django 4.0.5 on 2022-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sports_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sport', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('player', models.ManyToManyField(blank=True, to='sports.sports')),
            ],
        ),
        migrations.CreateModel(
            name='sports_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sport', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('player_choice', models.ManyToManyField(blank=True, to='sports.sports')),
            ],
        ),
    ]
