# Generated by Django 4.0.5 on 2022-06-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_rename_sports_sports_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
            options={
                'ordering': ['player_name'],
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('teacher_students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.player')),
            ],
            options={
                'ordering': ['teacher_name'],
            },
        ),
        migrations.RemoveField(
            model_name='sports_teacher',
            name='player',
        ),
        migrations.RenameField(
            model_name='sports_name',
            old_name='name',
            new_name='sport_name',
        ),
        migrations.RemoveField(
            model_name='sports_name',
            name='age',
        ),
        migrations.RemoveField(
            model_name='sports_name',
            name='player_choice',
        ),
        migrations.RemoveField(
            model_name='sports_name',
            name='sport',
        ),
        migrations.DeleteModel(
            name='sports_player',
        ),
        migrations.DeleteModel(
            name='sports_teacher',
        ),
        migrations.AddField(
            model_name='player',
            name='sports_choosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sports_name'),
        ),
    ]
