# Generated by Django 4.0.5 on 2022-06-07 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_player_teacher_remove_sports_teacher_player_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.RemoveField(
            model_name='player',
            name='sports_choosen',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_students',
        ),
        migrations.RenameModel(
            old_name='sports_name',
            new_name='sports',
        ),
        migrations.CreateModel(
            name='teacher_sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.ManyToManyField(blank=True, to='sports.sports')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='player_sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.player')),
                ('sport', models.ManyToManyField(blank=True, to='sports.sports')),
            ],
        ),
    ]
